### ISSUE TITLE
define_urban() island classification

### ISSUE THREAD

**Issue by ffeerriiss** [PATH-Global-Health/MNTD-tech-docs#16]
Hello!

I can't include @ht1212 as an assignee for some reason... This is a very limited issue that might be user error: I'm not having luck classifying an island. It has missing data in neighboring cells, and I'm not sure if this could be why. Or does each cell in the cluster need to meet the density threshold for those that exceed it to count as urban? If yes, that's what's going on! Here are the data I'm working with:

https://path.box.com/s/a0ov9j52so9v3f0swepcugz7jdqwwjjh
https://path.box.com/s/oekf941pnswc77va6ny9sbus1l1i6h5w

**Comment by justinmillar** [comment]
I believe a cell that exceeds the `rururb_cutoff` needs to be touching at least one other cell that also exceeds the cutoff to be included in a cluster, and if the whole cluster exceeds the `min_urbsize` then all the populated cells will be classified as "Urban." I'm pretty sure that only cells with populations get classified, so the NA shouldn't matter unless they fragment pixels (in which case we would classify the populated pixels as "Rural").

Could you post a plot of the island and population raster?

**Comment by ffeerriiss** [comment]
I think this was a false alarm--sorry, y'all! The total population of the cluster is right over 5k (urban), but one cell is under the density threshold (300 people/sq km). Without that cell the population of the cluster doesn't meet 5k.

![Likoma](https://github.com/PATH-Global-Health/MNTD-tech-docs/assets/57730697/7fcfb949-dc54-4af8-8c8a-0cb044b2adc2)
